services:
  - type: web
    name: abic-payroll
    env: python
    autoDeploy: true
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 3 --bind 0.0.0.0:$PORT
